hooks:
  all:
    pre:
      - type: drift_create_issue
        provider: aws
        role_arn: "arn:aws:iam::017777978390:role/terrateam"
drift:
  enabled: true
  reconcile: true
  schedule: hourly        
