hooks:
  all:
    pre:
      - type: oidc
        provider: aws
        role_arn: "arn:aws:iam::017777978390:role/terrateam"
drift:
  enabled: true
  reconcile: true
  schedule: hourly
apply_requirements:
  create_pending_apply_check: true
  checks:
    - tag_query: ''
      approved:
        enabled: false
        any_of: []
        any_of_count: 1
        all_of: []
      merge_conflicts:
        enabled: true
      status_checks:
        enabled: true
        ignore_matching: []
