hooks:
  all:
    pre:
      - type: oidc
        provider: aws
        role_arn: "arn:aws:iam::017777978390:role/terrateam"
drift:
- tag_query: "dir:production"
  enabled: true
  reconcile: true
  schedule: hourly        
